# Generated by Django 2.1.5 on 2019-06-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfname', models.CharField(max_length=50)),
                ('clname', models.CharField(max_length=50)),
                ('cmail', models.CharField(max_length=50)),
                ('cpass', models.CharField(max_length=50)),
                ('cdob', models.CharField(max_length=50)),
                ('ccontact', models.IntegerField(max_length=50)),
                ('cgender', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'custinfo',
            },
        ),
    ]
