# Generated by Django 2.1.5 on 2019-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessStore', '0002_custinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='strengthprod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stprodtype', models.CharField(max_length=50)),
                ('stprodweight', models.CharField(max_length=50)),
                ('stprodprice', models.FloatField(default=0.0)),
                ('stprodpic', models.ImageField(default='upload pic', upload_to='static/Images/')),
            ],
            options={
                'db_table': 'strengthprod',
            },
        ),
        migrations.AlterField(
            model_name='custinfo',
            name='ccontact',
            field=models.CharField(max_length=50),
        ),
    ]
